# Intro Python


In [10]:
x = 5
y = "Hola"

print(type(x))
print(type(y))

<class 'int'>
<class 'str'>


In [ ]:
c = "Hola mundo"
print(c)

Hola m,undo


In [12]:
print("Hola\nmundo") # Salto de linea
print("Hola\tmundo") # Tabulacion

Hola
mundo
Hola	mundo


In [13]:
e = 23
e

23

# Tipos de datos


In [14]:
print(type(5))
print(type(3.14))
print(type("Hola"))
print(type([1,2,3]))
print(type({'a':1, 'b':2}))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'dict'>


# Operaciones


In [15]:
s = 3 + 2
s2 = 3 + 2.0
print(s2)

5.0


In [16]:
r = 10 - 7
r2 = 10.5 - 3.2
print(r2)

7.3


In [17]:
n = -7
x = 5
y = -x
print(y)

-5


In [18]:
m = 2 * 6
m2 = 2.5 * 4
print(m2)

10.0


In [ ]:
e1 = 2**6
e2 = 9**0.5
print(e2)

15.625


In [ ]:
d = 3.5/2
d2 = 7/2
print(d2)

In [22]:
de = 3.5//2
de2 = -3.5//2
print(de2)

-2.0


In [23]:
mod = 7 % 2
print(mod)

1


# STR y CHAR


In [24]:
miTexto = "Hola"
miTexto

'Hola'

In [25]:
miChar = '02'
miChar

'02'

In [27]:
concatenacion = miTexto + miChar
concatenacion

'Hola02'

In [ ]:
miTexto + " Mundo"

'HolaMundo'

# Listas


In [32]:
Lista = [1, "Hola", 3.14]
Lista[1]

'Hola'

In [36]:
miLista = [1,2]

In [34]:
Lista*4

[1, 'Hola', 3.14, 1, 'Hola', 3.14, 1, 'Hola', 3.14, 1, 'Hola', 3.14]

In [37]:
Lista + miLista

[1, 'Hola', 3.14, 1, 2]

# Librerias


In [39]:
import numpy as np

In [40]:
lista_normal = [1,2,3,4,5]
vector_np = np.array(lista_normal)

print("Arreglo de NumPy:", vector_np)
print("Tipo de dato del arreglo:", type(vector_np))

Arreglo de NumPy: [1 2 3 4 5]
Tipo de dato del arreglo: <class 'numpy.ndarray'>


# Arreglos basicos


In [48]:
vector = np.array([1,2,3,4,5])
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
ceros = np.zeros((3,4))
unos = np.ones((2,3))
identidad = np.eye(4)
lineal = np.linspace(0, 1, 5)
rango = np.arange(0, 11, 2)

print("Vector de NumPy:", vector)
print("Rango de valores:", rango)
print("Valores linealmente espaciados:", lineal)
print("Matriz de NumPy:\n", matriz)
print("Matriz de ceros:\n", ceros)
print("Matriz de unos:\n", unos)
print("Matriz identidad:\n", identidad)

Vector de NumPy: [1 2 3 4 5]
Rango de valores: [ 0  2  4  6  8 10]
Valores linealmente espaciados: [0.   0.25 0.5  0.75 1.  ]
Matriz de NumPy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]
Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Operaciones matemáticas básicas


In [50]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("Suma de vectores:", a + b)
print("Resta de vectores:", a - b)
print("Producto:", a * b)
print("Cociente:", a / b)
print("Potencia:", a ** 2)

print("Multiplicar por escalar:", a * 2)

Suma de vectores: [11 22 33 44]
Resta de vectores: [ 9 18 27 36]
Producto: [ 10  40  90 160]
Cociente: [10. 10. 10. 10.]
Potencia: [ 100  400  900 1600]
Multiplicar por escalar: [20 40 60 80]


In [51]:
matriz = np.array([[1,2,3], [4,5,6]])

print("Matriz:\n", matriz)

print("Suma total:", np.sum(matriz))
print("Suma por filas:", np.sum(matriz, axis=1))
print("Suma por columnas:", np.sum(matriz, axis=0))

print("Media total:", np.mean(matriz))
print("Mínimo:", np.min(matriz))
print("Máximo:", np.max(matriz))
print("Desviación estándar:", np.std(matriz))

Matriz:
 [[1 2 3]
 [4 5 6]]
Suma total: 21
Suma por filas: [ 6 15]
Suma por columnas: [5 7 9]
Media total: 3.5
Mínimo: 1
Máximo: 6
Desviación estándar: 1.707825127659933


In [52]:
edades = np.array([25, 30, 35, 40, 45])
peso = np.array([70, 80, 90, 100, 110])
estatura = np.array([1.75, 1.80, 1.65, 1.70, 1.85])

BMI = peso/(estatura ** 2)
print("Índice de Masa Corporal (BMI):", BMI)

Índice de Masa Corporal (BMI): [22.85714286 24.69135802 33.05785124 34.60207612 32.14024836]
